apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: model
spec:
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: model
    spec:
      containers:
        - image: model
          imagePullPolicy: Never
          name: model
          ports:
            - containerPort: 9001
